version: '3'

services:
  node:
    image: node:18-alpine
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    user: 1000:1000

